### ISSUE TITLE
[Feature Request] Impl std::error::Error for fondant::FondantError

### ISSUE THREAD

**Issue by unknownue** [NerdyPepper/fondant#3]
To cast high level error(e.g. the application level error) to lower level error(e.g. `fondant::FondantError`) for crate like `thiserror`, it's necessary to implement `std::error::Error` trait.

**Comment by oppiliappan** [comment]
Done! As of `fondant v0.1.2`, `FondantError` implements `std::error::Error` and displays useful text messages on `eprintln!`. 

Thank you for the suggestion!
